# APPENDIX A Advanced NumPy

## A.3 Broadcasting

In [2]:
import pandas as pd
import numpy as np

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [6]:
arr = np.random.randn(4, 3)

In [7]:
arr.mean(0)

array([ 0.13332621, -0.59839475, -0.55649893])

In [8]:
demeaned = arr - arr.mean(0)

In [9]:
demeaned

array([[-0.70199735,  0.88723449, -0.15776117],
       [-0.23816262,  0.28617891, -0.01959706],
       [-0.35140164, -0.4695548 ,  1.6997408 ],
       [ 1.2915616 , -0.7038586 , -1.52238256]])

In [10]:
demeaned.mean(0)

array([0., 0., 0.])

In [11]:
arr

array([[-0.56867114,  0.28883973, -0.7142601 ],
       [-0.10483641, -0.31221585, -0.57609599],
       [-0.21807543, -1.06794955,  1.14324187],
       [ 1.42488781, -1.30225335, -2.07888149]])

In [12]:
row_means = arr.mean(1)

In [13]:
row_means.shape

(4,)

In [14]:
row_means.reshape((4, 1))

array([[-0.33136384],
       [-0.33104942],
       [-0.04759437],
       [-0.65208234]])

In [15]:
demeaned = arr - row_means.reshape((4, 1))

In [16]:
demeaned.mean(1)

array([-3.70074342e-17,  0.00000000e+00,  0.00000000e+00,  1.48029737e-16])

# A.6 More About Sorting

In [17]:
arr = np.random.randn(6)

In [18]:
arr.sort()

In [19]:
arr

array([-0.77745829, -0.62689773,  0.37103647,  0.51708313,  1.00721491,
        1.1540744 ])

In [20]:
arr = np.random.randn(3, 5)

In [21]:
arr

array([[ 1.43236425, -2.31268604, -0.75167944, -0.63406959, -1.38993176],
       [-0.44652142, -1.81287548, -0.7527317 , -1.26235818, -0.4700119 ],
       [ 0.79913055, -1.61319192, -2.42052299,  0.93514018,  1.80604775]])

In [22]:
arr[:, 0].sort()  # Sort first column values in-place

In [23]:
arr

array([[-0.44652142, -2.31268604, -0.75167944, -0.63406959, -1.38993176],
       [ 0.79913055, -1.81287548, -0.7527317 , -1.26235818, -0.4700119 ],
       [ 1.43236425, -1.61319192, -2.42052299,  0.93514018,  1.80604775]])

In [24]:
arr = np.random.randn(5)

In [25]:
arr

array([ 0.01051716, -0.11533023, -0.08020311, -0.50997955,  2.24051399])

In [26]:
np.sort(arr)

array([-0.50997955, -0.11533023, -0.08020311,  0.01051716,  2.24051399])

In [27]:
arr

array([ 0.01051716, -0.11533023, -0.08020311, -0.50997955,  2.24051399])

In [28]:
arr = np.random.randn(3, 5)

In [29]:
arr

array([[-0.66652024, -0.88675037,  0.5509589 ,  0.07227   ,  0.09353217],
       [ 1.50404242,  1.52064211, -1.52736813, -0.09808363, -1.70862064],
       [ 0.06136665,  2.17430158, -1.32187184, -1.56908533, -0.56795518]])

In [30]:
arr.sort(axis=1)

In [31]:
arr

array([[-0.88675037, -0.66652024,  0.07227   ,  0.09353217,  0.5509589 ],
       [-1.70862064, -1.52736813, -0.09808363,  1.50404242,  1.52064211],
       [-1.56908533, -1.32187184, -0.56795518,  0.06136665,  2.17430158]])

In [32]:
arr[:, ::-1]

array([[ 0.5509589 ,  0.09353217,  0.07227   , -0.66652024, -0.88675037],
       [ 1.52064211,  1.50404242, -0.09808363, -1.52736813, -1.70862064],
       [ 2.17430158,  0.06136665, -0.56795518, -1.32187184, -1.56908533]])

## Indirect Sorts: argsort and lexsort

In [33]:
values = np.array([5, 0, 1, 3, 2])

In [34]:
indexer = values.argsort()