# CHAPTER 4 NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
 %time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 43 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.47 s


## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [2]:
import numpy as np

In [3]:
# Generate some random data
data = np.random.randn(2, 3)

In [4]:
data

array([[ 0.49022393, -0.86431911,  0.05617638],
       [-1.02871793, -1.3629608 , -1.22618866]])

In [5]:
data * 10

array([[  4.90223931,  -8.64319107,   0.56176377],
       [-10.28717935, -13.62960797, -12.26188659]])

In [6]:
data + data

array([[ 0.98044786, -1.72863821,  0.11235275],
       [-2.05743587, -2.72592159, -2.45237732]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

## Creating ndarrays

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[9.36627965e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.75983079e+164]],

       [[6.25525431e-091, 2.46488553e+184],
        [2.81260561e-033, 1.53678233e-051],
        [3.99910963e+252, 1.33532084e+165]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [37]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [40]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [41]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [46]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
empty_uint32 = np.empty(8, dtype='u4')

In [4]:
empty_uint32

array([539921408,       606,   7077989,   6029420,   3211382,   3145774,
         3866716,   3801155], dtype=uint32)

## Arithmetic with NumPy Arrays

In [5]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [6]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [10]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [11]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [12]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [13]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [14]:
arr = np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [18]:
arr[5:8] = 12

In [19]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [20]:
arr_slice = arr[5:8]

In [21]:
arr_slice

array([12, 12, 12])

In [22]:
arr_slice[1] = 12345

In [23]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [24]:
arr_slice[:] = 64

In [25]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [27]:
arr2d[2]

array([7, 8, 9])

In [28]:
arr2d[0][2]

3

In [29]:
arr2d[0, 2]

3

In [30]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [31]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
old_values = arr3d[0].copy()

In [34]:
arr3d[0] = 42

In [35]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[0] = old_values

In [37]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[1, 0]

array([7, 8, 9])

In [39]:
x = arr3d[1]

In [40]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [41]:
x[0]

array([7, 8, 9])

### Indexing with slices

In [42]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [43]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [44]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [47]:
arr2d[1, :2]

array([4, 5])

In [48]:
arr2d[:2, 2]

array([3, 6])

In [49]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [50]:
arr2d[:2, 1:] = 0

In [51]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [52]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [53]:
data = np.random.randn(7, 4)

In [54]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[ 0.16799762,  0.218631  , -1.08046971,  0.20080374],
       [-0.90964909, -0.33616724, -0.3013769 ,  1.07317325],
       [ 0.01730153,  1.09266612, -0.98103898,  0.72795641],
       [-0.48571416, -0.77413786,  0.38524111, -0.2135952 ],
       [ 0.58296451, -0.73847347,  0.5125531 , -0.45391518],
       [-0.59618754, -1.02067356, -0.89113043,  0.37665512],
       [ 0.86920611,  2.62952131,  0.83144643, -1.42262482]])

In [56]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [57]:
data[names == 'Bob']

array([[ 0.16799762,  0.218631  , -1.08046971,  0.20080374],
       [-0.48571416, -0.77413786,  0.38524111, -0.2135952 ]])

In [58]:
data[names == 'Bob', 2:]

array([[-1.08046971,  0.20080374],
       [ 0.38524111, -0.2135952 ]])

In [59]:
 data[names == 'Bob', 3]

array([ 0.20080374, -0.2135952 ])

In [60]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [61]:
data[~(names == 'Bob')]

array([[-0.90964909, -0.33616724, -0.3013769 ,  1.07317325],
       [ 0.01730153,  1.09266612, -0.98103898,  0.72795641],
       [ 0.58296451, -0.73847347,  0.5125531 , -0.45391518],
       [-0.59618754, -1.02067356, -0.89113043,  0.37665512],
       [ 0.86920611,  2.62952131,  0.83144643, -1.42262482]])

In [62]:
cond = names == 'Bob'

In [63]:
data[~cond]

array([[-0.90964909, -0.33616724, -0.3013769 ,  1.07317325],
       [ 0.01730153,  1.09266612, -0.98103898,  0.72795641],
       [ 0.58296451, -0.73847347,  0.5125531 , -0.45391518],
       [-0.59618754, -1.02067356, -0.89113043,  0.37665512],
       [ 0.86920611,  2.62952131,  0.83144643, -1.42262482]])

In [64]:
mask = (names == 'Bob') | (names == 'Will')

In [65]:
mask

array([ True, False,  True,  True,  True, False, False])

In [66]:
data[mask]

array([[ 0.16799762,  0.218631  , -1.08046971,  0.20080374],
       [ 0.01730153,  1.09266612, -0.98103898,  0.72795641],
       [-0.48571416, -0.77413786,  0.38524111, -0.2135952 ],
       [ 0.58296451, -0.73847347,  0.5125531 , -0.45391518]])

In [67]:
data[data < 0] = 0

In [68]:
data

array([[0.16799762, 0.218631  , 0.        , 0.20080374],
       [0.        , 0.        , 0.        , 1.07317325],
       [0.01730153, 1.09266612, 0.        , 0.72795641],
       [0.        , 0.        , 0.38524111, 0.        ],
       [0.58296451, 0.        , 0.5125531 , 0.        ],
       [0.        , 0.        , 0.        , 0.37665512],
       [0.86920611, 2.62952131, 0.83144643, 0.        ]])

In [69]:
data[names != 'Joe'] = 7

In [70]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 1.07317325],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.37665512],
       [0.86920611, 2.62952131, 0.83144643, 0.        ]])

## Fancy Indexing

In [71]:
arr = np.empty((8, 4))

In [72]:
for i in range(8):
    arr[i] = i

In [73]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [76]:
arr = np.arange(32).reshape((8, 4))

In [77]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [78]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [79]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [89]:
arr = np.arange(15).reshape((3, 5))

In [90]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [83]:
arr = np.random.randn(6, 3)

In [84]:
arr

array([[ 0.80732256, -0.34373532,  1.36337714],
       [-0.02313576,  0.22575988, -0.26193318],
       [-2.45203533, -0.12743642, -1.29512956],
       [ 0.19886096, -0.34459563, -0.20473198],
       [ 0.7139329 ,  0.31073029, -0.15859908],
       [ 0.45794792, -0.66852351,  0.87311174]])

In [92]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [93]:
arr = np.arange(16).reshape((2, 2, 4))

In [97]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [100]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [102]:
arr = np.arange(10)

In [103]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [105]:
 np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [106]:
x = np.random.randn(8)

In [107]:
y = np.random.randn(8)

In [108]:
x

array([ 0.96739978, -0.16733992,  0.69215216,  0.06001025, -0.13362121,
       -0.56979869, -2.0778234 ,  1.17045357])

In [109]:
y

array([-0.14602872, -0.86148394,  1.1517121 , -0.38772355,  0.03031591,
        1.19942526,  1.14064489,  0.98452498])

In [110]:
np.maximum(x, y)

array([ 0.96739978, -0.16733992,  1.1517121 ,  0.06001025,  0.03031591,
        1.19942526,  1.14064489,  1.17045357])

In [112]:
arr = np.random.randn(7) * 5

In [113]:
arr

array([ 4.23550526,  3.4616094 ,  2.52050358,  5.77827958, -4.28651085,
       -4.95331396,  2.53545223])

In [114]:
remainder, whole_part = np.modf(arr)

In [115]:
remainder

array([ 0.23550526,  0.4616094 ,  0.52050358,  0.77827958, -0.28651085,
       -0.95331396,  0.53545223])

In [116]:
whole_part

array([ 4.,  3.,  2.,  5., -4., -4.,  2.])

In [117]:
arr

array([ 4.23550526,  3.4616094 ,  2.52050358,  5.77827958, -4.28651085,
       -4.95331396,  2.53545223])

In [118]:
np.sqrt(arr)

C:\Users\Min-Yao\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.05803432, 1.86054008, 1.58760939, 2.40380523,        nan,
              nan, 1.59231034])

In [119]:
np.sqrt(arr, arr)

C:\Users\Min-Yao\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.05803432, 1.86054008, 1.58760939, 2.40380523,        nan,
              nan, 1.59231034])

In [120]:
arr

array([2.05803432, 1.86054008, 1.58760939, 2.40380523,        nan,
              nan, 1.59231034])